version: '3.8'

services:
  web:
    container_name: web
    build: frontend
    image: shambhaveesrivastava12/frontend-repo:cc-frontend
    networks:
      - object-detection
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - yolo5

  yolo5:
    container_name: yolo5
    build: yolo5
    networks:
      - object-detection
    image: shambhaveesrivastava12/yolo5-repo:cc-yolo5
    environment:
      - AWS_ACCESS_KEY_ID="AKIA4NYEYP6K67NH47FR"
      - AWS_SECRET_ACCESS_KEY="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"
      - AWS_DEFAULT_REGION="us-east-2"
    ports:
      - "8081:8081"

  mongodb:
    container_name: mongodb
    image: mongo:latest

    networks:
      - object-detection
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - ./mongo/data:/data/db

  polybot:
    container_name: polybot
    image: shambhaveesrivastava12/polybotlatest_repo:cc-poly
    networks:
      - object-detection
    depends_on:
      - yolo5


volumes:
  mongodb:
    driver: local

networks:
  object-detection:
    name: object-detection
    driver: bridge